/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    products: Product;
    categories: Category;
    orders: Order;
    carts: Cart;
    reviews: Review;
    coupons: Coupon;
    wishlists: Wishlist;
    posts: Post;
    notifications: Notification;
    'shipping-zones': ShippingZone;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    carts: CartsSelect<false> | CartsSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    coupons: CouponsSelect<false> | CouponsSelect<true>;
    wishlists: WishlistsSelect<false> | WishlistsSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    notifications: NotificationsSelect<false> | NotificationsSelect<true>;
    'shipping-zones': ShippingZonesSelect<false> | ShippingZonesSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {
    'site-settings': SiteSetting;
    navigation: Navigation;
    homepage: Homepage;
    'about-page': AboutPage;
    'contact-page': ContactPage;
    'cart-page': CartPage;
    'order-success': OrderSuccess;
    'blog-page': BlogPage;
    'trusearch-settings': TrusearchSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    homepage: HomepageSelect<false> | HomepageSelect<true>;
    'about-page': AboutPageSelect<false> | AboutPageSelect<true>;
    'contact-page': ContactPageSelect<false> | ContactPageSelect<true>;
    'cart-page': CartPageSelect<false> | CartPageSelect<true>;
    'order-success': OrderSuccessSelect<false> | OrderSuccessSelect<true>;
    'blog-page': BlogPageSelect<false> | BlogPageSelect<true>;
    'trusearch-settings': TrusearchSettingsSelect<false> | TrusearchSettingsSelect<true>;
  };
  locale: 'en';
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  firstName: string;
  lastName: string;
  phone?: string | null;
  role: 'customer' | 'vendor' | 'admin';
  avatar?: (number | null) | Media;
  loyaltyPoints?: number | null;
  stripeCustomerId?: string | null;
  isEmailVerified?: boolean | null;
  addresses?:
    | {
        label?: string | null;
        line1?: string | null;
        line2?: string | null;
        city?: string | null;
        state?: string | null;
        country?: string | null;
        zip?: string | null;
        isDefault?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  name: string;
  slug?: string | null;
  description: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Max 200 characters
   */
  shortDesc?: string | null;
  status: 'draft' | 'active' | 'archived';
  categories?: (number | Category)[] | null;
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  vendor?: (number | null) | User;
  images?:
    | {
        image?: (number | null) | Media;
        altText?: string | null;
        isPrimary?: boolean | null;
        id?: string | null;
      }[]
    | null;
  pricing: {
    price: number;
    comparePrice?: number | null;
    costPrice?: number | null;
    currency?: ('USD' | 'EUR' | 'GBP' | 'INR') | null;
  };
  inventory?: {
    trackStock?: boolean | null;
    stock?: number | null;
    lowStockAlert?: number | null;
    sku?: string | null;
    barcode?: string | null;
    weight?: number | null;
    dimensions?: {
      length?: number | null;
      width?: number | null;
      height?: number | null;
    };
  };
  variants?:
    | {
        name?: string | null;
        options?:
          | {
              label?: string | null;
              price?: number | null;
              stock?: number | null;
              sku?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  seo?: {
    metaTitle?: string | null;
    metaDesc?: string | null;
    ogImage?: (number | null) | Media;
  };
  shipping?: {
    isFreeShipping?: boolean | null;
    shippingClass?: ('standard' | 'express' | 'heavy') | null;
  };
  isDigital?: boolean | null;
  digitalFile?: (number | null) | Media;
  /**
   * Product specifications shown in the Specifications tab
   */
  specs?:
    | {
        label?: string | null;
        value?: string | null;
        id?: string | null;
      }[]
    | null;
  ratings?: {
    average?: number | null;
    count?: number | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  slug?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  image?: (number | null) | Media;
  /**
   * Display text shown on category card, e.g. "240+ styles"
   */
  itemCount?: string | null;
  parent?: (number | null) | Category;
  metaTitle?: string | null;
  metaDesc?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  orderNumber?: string | null;
  user: number | User;
  status: 'pending' | 'confirmed' | 'processing' | 'shipped' | 'delivered' | 'cancelled' | 'refunded';
  items: {
    product?: (number | null) | Product;
    variantLabel?: string | null;
    quantity?: number | null;
    unitPrice?: number | null;
    totalPrice?: number | null;
    snapshot?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    id?: string | null;
  }[];
  subtotal?: number | null;
  discount?: number | null;
  tax?: number | null;
  shippingCost?: number | null;
  total?: number | null;
  coupon?: (number | null) | Coupon;
  currency?: string | null;
  shippingAddress?: {
    name?: string | null;
    line1?: string | null;
    line2?: string | null;
    city?: string | null;
    state?: string | null;
    country?: string | null;
    zip?: string | null;
    phone?: string | null;
  };
  payment?: {
    provider?: ('stripe' | 'paypal' | 'cod') | null;
    stripePaymentIntentId?: string | null;
    stripeChargeId?: string | null;
    status?: ('pending' | 'paid' | 'failed' | 'refunded') | null;
    paidAt?: string | null;
  };
  shippingInfo?: {
    carrier?: string | null;
    trackingNumber?: string | null;
    estimatedDelivery?: string | null;
    shippedAt?: string | null;
    deliveredAt?: string | null;
  };
  notes?: string | null;
  statusHistory?:
    | {
        status?: string | null;
        note?: string | null;
        updatedAt?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coupons".
 */
export interface Coupon {
  id: number;
  code: string;
  type: 'percentage' | 'fixed' | 'freeShipping';
  value?: number | null;
  minOrderValue?: number | null;
  maxUses?: number | null;
  usedCount?: number | null;
  usedBy?: (number | User)[] | null;
  expiresAt?: string | null;
  isActive?: boolean | null;
  products?: (number | Product)[] | null;
  categories?: (number | Category)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carts".
 */
export interface Cart {
  id: number;
  user?: (number | null) | User;
  sessionId?: string | null;
  items?:
    | {
        product?: (number | null) | Product;
        variant?: string | null;
        quantity?: number | null;
        addedAt?: string | null;
        id?: string | null;
      }[]
    | null;
  coupon?: (number | null) | Coupon;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: number;
  product: number | Product;
  user: number | User;
  rating: number;
  title: string;
  body: string;
  images?:
    | {
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  isVerified?: boolean | null;
  isApproved?: boolean | null;
  reply?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wishlists".
 */
export interface Wishlist {
  id: number;
  user: number | User;
  name?: string | null;
  isPublic?: boolean | null;
  items?:
    | {
        product?: (number | null) | Product;
        addedAt?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  slug?: string | null;
  excerpt?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  coverImage?: (number | null) | Media;
  author?: (number | null) | User;
  categories?: (number | Category)[] | null;
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  status?: ('draft' | 'published') | null;
  publishedAt?: string | null;
  seo?: {
    metaTitle?: string | null;
    metaDesc?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications".
 */
export interface Notification {
  id: number;
  user: number | User;
  type?: ('order_update' | 'promotion' | 'stock_alert' | 'review_reply') | null;
  title?: string | null;
  message?: string | null;
  isRead?: boolean | null;
  link?: string | null;
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shipping-zones".
 */
export interface ShippingZone {
  id: number;
  name: string;
  countries?:
    | {
        /**
         * ISO 3166-1 alpha-2
         */
        country?: string | null;
        id?: string | null;
      }[]
    | null;
  rates?:
    | {
        name?: string | null;
        price?: number | null;
        minDays?: number | null;
        maxDays?: number | null;
        freeAbove?: number | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'carts';
        value: number | Cart;
      } | null)
    | ({
        relationTo: 'reviews';
        value: number | Review;
      } | null)
    | ({
        relationTo: 'coupons';
        value: number | Coupon;
      } | null)
    | ({
        relationTo: 'wishlists';
        value: number | Wishlist;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'notifications';
        value: number | Notification;
      } | null)
    | ({
        relationTo: 'shipping-zones';
        value: number | ShippingZone;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  phone?: T;
  role?: T;
  avatar?: T;
  loyaltyPoints?: T;
  stripeCustomerId?: T;
  isEmailVerified?: T;
  addresses?:
    | T
    | {
        label?: T;
        line1?: T;
        line2?: T;
        city?: T;
        state?: T;
        country?: T;
        zip?: T;
        isDefault?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  shortDesc?: T;
  status?: T;
  categories?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  vendor?: T;
  images?:
    | T
    | {
        image?: T;
        altText?: T;
        isPrimary?: T;
        id?: T;
      };
  pricing?:
    | T
    | {
        price?: T;
        comparePrice?: T;
        costPrice?: T;
        currency?: T;
      };
  inventory?:
    | T
    | {
        trackStock?: T;
        stock?: T;
        lowStockAlert?: T;
        sku?: T;
        barcode?: T;
        weight?: T;
        dimensions?:
          | T
          | {
              length?: T;
              width?: T;
              height?: T;
            };
      };
  variants?:
    | T
    | {
        name?: T;
        options?:
          | T
          | {
              label?: T;
              price?: T;
              stock?: T;
              sku?: T;
              id?: T;
            };
        id?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDesc?: T;
        ogImage?: T;
      };
  shipping?:
    | T
    | {
        isFreeShipping?: T;
        shippingClass?: T;
      };
  isDigital?: T;
  digitalFile?: T;
  specs?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  ratings?:
    | T
    | {
        average?: T;
        count?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  image?: T;
  itemCount?: T;
  parent?: T;
  metaTitle?: T;
  metaDesc?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  orderNumber?: T;
  user?: T;
  status?: T;
  items?:
    | T
    | {
        product?: T;
        variantLabel?: T;
        quantity?: T;
        unitPrice?: T;
        totalPrice?: T;
        snapshot?: T;
        id?: T;
      };
  subtotal?: T;
  discount?: T;
  tax?: T;
  shippingCost?: T;
  total?: T;
  coupon?: T;
  currency?: T;
  shippingAddress?:
    | T
    | {
        name?: T;
        line1?: T;
        line2?: T;
        city?: T;
        state?: T;
        country?: T;
        zip?: T;
        phone?: T;
      };
  payment?:
    | T
    | {
        provider?: T;
        stripePaymentIntentId?: T;
        stripeChargeId?: T;
        status?: T;
        paidAt?: T;
      };
  shippingInfo?:
    | T
    | {
        carrier?: T;
        trackingNumber?: T;
        estimatedDelivery?: T;
        shippedAt?: T;
        deliveredAt?: T;
      };
  notes?: T;
  statusHistory?:
    | T
    | {
        status?: T;
        note?: T;
        updatedAt?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carts_select".
 */
export interface CartsSelect<T extends boolean = true> {
  user?: T;
  sessionId?: T;
  items?:
    | T
    | {
        product?: T;
        variant?: T;
        quantity?: T;
        addedAt?: T;
        id?: T;
      };
  coupon?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  product?: T;
  user?: T;
  rating?: T;
  title?: T;
  body?: T;
  images?:
    | T
    | {
        image?: T;
        id?: T;
      };
  isVerified?: T;
  isApproved?: T;
  reply?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coupons_select".
 */
export interface CouponsSelect<T extends boolean = true> {
  code?: T;
  type?: T;
  value?: T;
  minOrderValue?: T;
  maxUses?: T;
  usedCount?: T;
  usedBy?: T;
  expiresAt?: T;
  isActive?: T;
  products?: T;
  categories?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wishlists_select".
 */
export interface WishlistsSelect<T extends boolean = true> {
  user?: T;
  name?: T;
  isPublic?: T;
  items?:
    | T
    | {
        product?: T;
        addedAt?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  content?: T;
  coverImage?: T;
  author?: T;
  categories?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  status?: T;
  publishedAt?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDesc?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications_select".
 */
export interface NotificationsSelect<T extends boolean = true> {
  user?: T;
  type?: T;
  title?: T;
  message?: T;
  isRead?: T;
  link?: T;
  createdAt?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shipping-zones_select".
 */
export interface ShippingZonesSelect<T extends boolean = true> {
  name?: T;
  countries?:
    | T
    | {
        country?: T;
        id?: T;
      };
  rates?:
    | T
    | {
        name?: T;
        price?: T;
        minDays?: T;
        maxDays?: T;
        freeAbove?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  tagline?: string | null;
  logo?: (number | null) | Media;
  favicon?: (number | null) | Media;
  currency?: ('USD' | 'EUR' | 'GBP' | 'INR') | null;
  timezone?: string | null;
  supportEmail?: string | null;
  supportPhone?: string | null;
  socialLinks?: {
    instagram?: string | null;
    twitter?: string | null;
    facebook?: string | null;
    youtube?: string | null;
    linkedin?: string | null;
  };
  maintenanceMode?: boolean | null;
  announcement?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  navItems?:
    | {
        label: string;
        link: string;
        openInNew?: boolean | null;
        children?:
          | {
              label?: string | null;
              link?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  footerLinks?:
    | {
        heading?: string | null;
        links?:
          | {
              label?: string | null;
              href?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  hero?: {
    heading?: string | null;
    subheading?: string | null;
    ctaText?: string | null;
    ctaLink?: string | null;
    secondaryCtaText?: string | null;
    secondaryCtaLink?: string | null;
    bgImage?: (number | null) | Media;
    /**
     * Stats shown below hero buttons (e.g. "10k+ Products")
     */
    stats?:
      | {
          value?: string | null;
          label?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Select up to 6 categories to show in the homepage grid
   */
  featuredCategories?: (number | Category)[] | null;
  /**
   * Hand-pick products for the Featured carousel. Leave empty to show latest products.
   */
  featuredProducts?: (number | Product)[] | null;
  /**
   * Side-by-side promotional banners (max 2)
   */
  promoBanners?:
    | {
        /**
         * Small label above title, e.g. "New In"
         */
        label?: string | null;
        title?: string | null;
        image?: (number | null) | Media;
        link?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Trust badges shown below promo banners
   */
  trustBadges?:
    | {
        icon?: ('truck' | 'refresh' | 'shield' | 'headphones') | null;
        title?: string | null;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  newsletter?: {
    heading?: string | null;
    subheading?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page".
 */
export interface AboutPage {
  id: number;
  heroTitle?: string | null;
  heroImage?: (number | null) | Media;
  missionTitle?: string | null;
  missionText?: string | null;
  missionText2?: string | null;
  missionImage?: (number | null) | Media;
  /**
   * Key metrics shown in the stats row
   */
  stats?:
    | {
        value?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  teamHeading?: string | null;
  /**
   * Team members shown on the about page
   */
  team?:
    | {
        name?: string | null;
        role?: string | null;
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  ctaTitle?: string | null;
  ctaText?: string | null;
  ctaLink?: string | null;
  ctaButtonText?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page".
 */
export interface ContactPage {
  id: number;
  pageTitle?: string | null;
  pageDescription?: string | null;
  contactInfo?: {
    email?: string | null;
    phone?: string | null;
    address?: string | null;
    hours?: string | null;
  };
  /**
   * Frequently asked questions shown on the contact page
   */
  faq?:
    | {
        question?: string | null;
        answer?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cart-page".
 */
export interface CartPage {
  id: number;
  /**
   * Heading for the upsell section below the cart
   */
  upsellHeading?: string | null;
  /**
   * Hand-pick products shown in "You Might Also Like" on the cart page
   */
  upsellProducts?: (number | Product)[] | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "order-success".
 */
export interface OrderSuccess {
  id: number;
  heading?: string | null;
  subheading?: string | null;
  description?: string | null;
  stepsHeading?: string | null;
  /**
   * Steps shown after a successful order
   */
  steps?:
    | {
        text?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-page".
 */
export interface BlogPage {
  id: number;
  pageTitle?: string | null;
  pageDescription?: string | null;
  /**
   * Label shown on the first (featured) post
   */
  featuredLabel?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Configure the TruSearch engine connection and trigger a reindex of your collections from here.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trusearch-settings".
 */
export interface TrusearchSetting {
  id: number;
  /**
   * When off, no documents are pushed to the engine. Writes proceed normally.
   */
  enabled?: boolean | null;
  /**
   * Base URL of the TruSearch engine. Leaving this blank falls back to the value set via plugin options or TRUSEARCH_ENGINE_URL.
   */
  engineBaseUrl?: string | null;
  /**
   * Scoped API key (starts with tsk_). Stored in the database — only admins should have update access to this global.
   */
  engineApiKey?: string | null;
  /**
   * Used when a collection override does not specify its own indexId.
   */
  defaultIndexId?: string | null;
  /**
   * Select which collections to index. Writes to any collection not selected here are ignored.
   */
  indexedCollections?:
    | (
        | 'media'
        | 'products'
        | 'categories'
        | 'orders'
        | 'carts'
        | 'reviews'
        | 'coupons'
        | 'wishlists'
        | 'posts'
        | 'notifications'
        | 'shipping-zones'
      )[]
    | null;
  /**
   * Fine-tune indexing behavior per collection. Only collections you also select above are actually indexed.
   */
  collectionOverrides?:
    | {
        slug:
          | 'media'
          | 'products'
          | 'categories'
          | 'orders'
          | 'carts'
          | 'reviews'
          | 'coupons'
          | 'wishlists'
          | 'posts'
          | 'notifications'
          | 'shipping-zones';
        indexId?: string | null;
        titleField?: string | null;
        bodyField?: string | null;
        /**
         * Optional. Template like "/blog/{slug}" — tokens in {braces} are replaced with the document field of that name.
         */
        urlTemplate?: string | null;
        publishedField?: string | null;
        indexDrafts?: boolean | null;
        localized?: boolean | null;
        /**
         * If any rows are provided, only these field names are indexed.
         */
        includeFields?:
          | {
              fieldName: string;
              id?: string | null;
            }[]
          | null;
        excludeFields?:
          | {
              fieldName: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  tagline?: T;
  logo?: T;
  favicon?: T;
  currency?: T;
  timezone?: T;
  supportEmail?: T;
  supportPhone?: T;
  socialLinks?:
    | T
    | {
        instagram?: T;
        twitter?: T;
        facebook?: T;
        youtube?: T;
        linkedin?: T;
      };
  maintenanceMode?: T;
  announcement?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        label?: T;
        link?: T;
        openInNew?: T;
        children?:
          | T
          | {
              label?: T;
              link?: T;
              id?: T;
            };
        id?: T;
      };
  footerLinks?:
    | T
    | {
        heading?: T;
        links?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        heading?: T;
        subheading?: T;
        ctaText?: T;
        ctaLink?: T;
        secondaryCtaText?: T;
        secondaryCtaLink?: T;
        bgImage?: T;
        stats?:
          | T
          | {
              value?: T;
              label?: T;
              id?: T;
            };
      };
  featuredCategories?: T;
  featuredProducts?: T;
  promoBanners?:
    | T
    | {
        label?: T;
        title?: T;
        image?: T;
        link?: T;
        id?: T;
      };
  trustBadges?:
    | T
    | {
        icon?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  newsletter?:
    | T
    | {
        heading?: T;
        subheading?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  heroTitle?: T;
  heroImage?: T;
  missionTitle?: T;
  missionText?: T;
  missionText2?: T;
  missionImage?: T;
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  teamHeading?: T;
  team?:
    | T
    | {
        name?: T;
        role?: T;
        image?: T;
        id?: T;
      };
  ctaTitle?: T;
  ctaText?: T;
  ctaLink?: T;
  ctaButtonText?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page_select".
 */
export interface ContactPageSelect<T extends boolean = true> {
  pageTitle?: T;
  pageDescription?: T;
  contactInfo?:
    | T
    | {
        email?: T;
        phone?: T;
        address?: T;
        hours?: T;
      };
  faq?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cart-page_select".
 */
export interface CartPageSelect<T extends boolean = true> {
  upsellHeading?: T;
  upsellProducts?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "order-success_select".
 */
export interface OrderSuccessSelect<T extends boolean = true> {
  heading?: T;
  subheading?: T;
  description?: T;
  stepsHeading?: T;
  steps?:
    | T
    | {
        text?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-page_select".
 */
export interface BlogPageSelect<T extends boolean = true> {
  pageTitle?: T;
  pageDescription?: T;
  featuredLabel?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trusearch-settings_select".
 */
export interface TrusearchSettingsSelect<T extends boolean = true> {
  enabled?: T;
  engineBaseUrl?: T;
  engineApiKey?: T;
  defaultIndexId?: T;
  indexedCollections?: T;
  collectionOverrides?:
    | T
    | {
        slug?: T;
        indexId?: T;
        titleField?: T;
        bodyField?: T;
        urlTemplate?: T;
        publishedField?: T;
        indexDrafts?: T;
        localized?: T;
        includeFields?:
          | T
          | {
              fieldName?: T;
              id?: T;
            };
        excludeFields?:
          | T
          | {
              fieldName?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}